RentCar/urls.py
from django.contrib import admin
from django.urls import path, include

from rentcar_app.views import IndexView, CarDetailsView, contact, RentCarView, car_list, RentListView, RentDetailsView, \
    RentEditView, RentDeleteView, CarAddCreateView, CarUpdateView, CarDeleteView, AddLocationView, UserRentListView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', IndexView.as_view(), name='index'),
    path('car_add/', CarAddCreateView.as_view(), name='car_add'),
    path('car_list/', car_list, name='car_list'),
    path('car_details/<int:pk>/', CarDetailsView.as_view(), name='car_details'),
    path('car_update/<int:pk>/', CarUpdateView.as_view(), name='car_update'),
    path('car_delete/<int:pk>/', CarDeleteView.as_view(), name='car_delete'),
    path('location_add/', AddLocationView.as_view(), name='location_add'),
    path('rent_add/', RentCarView.as_view(), name='car_rent'),
    path('rent_list/', RentListView.as_view(), name='rent_list'),
    path('rent_details/<int:pk>/', RentDetailsView.as_view(), name='rent_details'),
    path('user_rent_list/', UserRentListView.as_view(), name='user_rent_list'),
    path('rent_edit/<int:pk>/', RentEditView.as_view(), name='rent_edit'),
    path('rent_delete/<int:pk>/', RentDeleteView.as_view(), name='rent_delete'),
    path('contact/', contact, name='contact'),
]

rentcar_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Profile(models.Model):  # model that expanse User Model
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    tel_num = models.IntegerField(null=True)
    address = models.CharField(max_length=128, null=True)
    city = models.CharField(max_length=64, null=True)
    zip_code = models.CharField(max_length=5, blank=True, null=True)

    def __str__(self):
        return str(self.user)

    def get_update_url(self):
        return reverse('profile_update', args=(self.pk,))


class Brand(models.Model):  # model connected with car brands
    BRANDS = (
        (0, 'Audi'),
        (1, 'BMW'),
        (2, 'Citroen'),
        (3, 'Fiat'),
        (4, 'Ford'),
        (5, 'Hyundai'),
        (6, 'Kia'),
        (7, 'Lexus'),
        (8, 'Mazda'),
        (9, 'Mercedes'),
        (10, 'Nissan'),
        (11, 'Opel'),
        (12, 'Renault'),
        (13, 'SEAT'),
        (14, 'Skoda'),
        (15, 'Tesla'),
        (16, 'Toyota'),
        (17, 'Volkswagen'),
        (18, 'Volvo'),
    )
    name = models.IntegerField(choices=BRANDS)

    def __str__(self):
        return self.get_name_display()


class Type(models.Model):   # model connected with car types
    TYPES = (
        (0, 'Convertible'),
        (1, 'Coupe'),
        (2, 'Hatchback'),
        (3, 'Minivan'),
        (4, 'Pickup Truck'),
        (5, 'Sedan'),
        (6, 'Sports Car'),
        (7, 'Station Wagon'),
        (8, 'SUV'),
    )
    name = models.IntegerField(choices=TYPES)

    def __str__(self):
        return self.get_name_display()


class Car(models.Model):   # Car model
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    model = models.CharField(max_length=64)
    type = models.ForeignKey(Type, on_delete=models.CASCADE)
    power = models.IntegerField()
    engine = models.DecimalField(max_digits=2, decimal_places=1, null=True, blank=True)
    year = models.DecimalField(max_digits=4, decimal_places=0)
    seats = models.IntegerField()
    GEARS = (
        (0, 'automatic'),
        (1, 'manual'))
    gears = models.IntegerField(choices=GEARS)
    FUELS = (
        (0, 'petrol'),
        (1, 'oil'),
        (2, 'petrol+LPG'),
        (3, 'hybrid'),
        (4, 'electric'))
    fuel = models.IntegerField(choices=FUELS)
    price_per_day = models.IntegerField()
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.brand} {self.model}"

    def get_update_url(self):
        return reverse('car_update', args=(self.pk,))

    def get_details_url(self):
        return reverse('car_details', args=(self.pk,))

    def get_delete_url(self):
        return reverse('car_delete', args=(self.pk,))


class Location(models.Model):  # Location Model
    name = models.CharField(max_length=64, unique=True)

    def __str__(self):
        return f"{self.name}"


class Rent(models.Model):  # Model which allows to reserve a car
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    location = models.ForeignKey(Location, on_delete=models.CASCADE)
    start_date = models.DateField(auto_now_add=False, auto_now=False)
    end_date = models.DateField(auto_now_add=False, auto_now=False)

    class Meta:
        unique_together = ('car', 'start_date', 'end_date')

    def get_edit_url(self):
        return reverse('rent_edit', args=(self.pk,))

    def get_details_url(self):
        return reverse('rent_details', args=(self.pk,))

    def get_delete_url(self):
        return reverse('rent_delete', args=(self.pk,))

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  {% block title %}
    <title>RentCar4U</title>
    {% endblock %}

  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/animate.css/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: Selecao - v4.7.0
  * Template URL: https://bootstrapmade.com/selecao-bootstrap-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top d-flex align-items-center ">
    <div class="container d-flex align-items-center justify-content-between">

      <div class="logo">
        <h1><a href="{% url "index" %}">RentCar4U</a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

      </div>
{% include "nav_bar.html" %}
    </div>
  </header><!-- End Header -->

  <main id="main">

    <section class="inner-page">
      <div class="container">
        <p>
          {% block content %}

          {% endblock %}
        </p>
      </div>
    </section>

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="container">
      <h3>RentCar4U</h3>
      <div class="copyright">
          &copy; Copyright <strong><span> <a href="https://www.linkedin.com/in/maciejstys1992/">Maciej Styś</a></span></strong> All Rights Reserved
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/selecao-bootstrap-template/ -->
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
      </div>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>

templates/car_details.html
{% extends "base.html" %}
{% block title %}
    <title>Car details | RentCar4U</title>
{% endblock %}

{% block content %}
    <h3>Car details:</h3>
    <p class="lead"><p>
    <ul class="list-unstyled">
        <li>Brand: {{ car.brand }}</li>
        <li>Model: {{ car.model }}</li>
        <li>Type: {{ car.type }}</li>
        <li>Power: {{ car.power }} HP</li>
        <li>Engine*: {{ car.engine }}</li>
        <li>Year: {{ car.year }}</li>
        <li>Number of seats: {{ car.seats }}</li>
        <li>Gears type: {{ car.get_gears_display }}</li>
        <li>Fuel type: {{ car.get_fuel_display }}</li>
        <li>Price per day: {{ car.price_per_day }} zł</li>
    </ul>
    <br>
    <p>*blank in case of electric or hybrid version</p>
{% endblock %}

templates/car_list.html
{% extends "base.html" %}
{% block title %}
    <title>Car list | RentCar4U</title>
{% endblock %}
{% block content %}

    <form method="get">
        {{ filter.form.as_p }}
        <input class="btn btn-secondary" type="submit" value="Filter"/>
    </form>

    <div>
        <p>
        <ul class="list-unstyled">
            {% for car in filter.qs %}
                <li><a href="{{ car.get_details_url }}">{{ car }} </a>
                    <a href="{{ car.get_update_url }}">[Edit] </a>
                    <a href="{{ car.get_delete_url }}">[Delete]</a></li>
            {% endfor %}
        </ul>
        </p>
    </div>
{% endblock %}

templates/car_rent.html
{% extends "base.html" %}
{% block title %}
    <title>Rent a car | RentCar4U</title>
{% endblock %}

{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        <label>Select Car:</label>
        <select name="car">
            {% for car in cars %}
                <option value="{{ car.id }}"> {{ car.brand }} {{ car.model }}
            {% endfor %}
            </option>
        </select><br>
        <label>Start date</label>
        <input type="date" id="start_date" name="start_date" max="3000-12-31"
               min="1000-01-01"><br>
        <label>End date</label>
        <input type="date" id="end_date" name="end_date" max="3000-12-31"
               min="1000-01-01"><br>
        <label>Location</label>
        <select name="location">
            {% for location in locations %}
                <option value="{{ location.id }}"> {{ location.name }}
            {% endfor %}
            </option>
        </select><br>
        </div>

        <button type="submit" class="btn btn-secondary">Reserve</button>
    </form><br>

    {% if error %}
        {{ error }}
    {% endif %}

{% endblock %}

templates/contact.html
{% extends "base.html" %}
{% block title %}
    <title>Contact | RentCar4U</title>
{% endblock %}
{% block content %}
    <h3>Company details:</h3>
    <p><RentCar4U®</p>
        <p>71-327 Szczecin, ul. Kochanowskiego 14</p>
        <p>Tel. num: (32) 22 33 444</p>
        <p>rentcar4u@gmail.pl</p>

{% endblock %}

templates/edit_profile.html
{% extends "base.html" %}
{% block title %}
    <title>Edit Profile | RentCar4U</title>
{% endblock %}
{% block content %}
<main class="px-3">
    <h3>Edit Profile:</h3>
    <form action="" method="POST">
        {% csrf_token %}
        <label>First name:</label>
        <input type="text" name="new_first_name"><br>
        <label>Last name:</label>
        <input type="text" name="new_last_name"><br>
        <label>Email:</label>
        <input type="text" name="new_email" required/><br>
        <label>Tel. number:</label>
        <input type="number" maxlength="10" max="9999999999" name="new_tel_num" required/><br>
        <label>Address:</label>
        <input type="text" name="new_address" required/><br>
        <label>City:</label>
        <input type="text" name="new_city" required/><br>
        <label>Zip code:</label>
        <input type="text" maxlength="5" name="new_zip_code" required/><br>
        <input type="submit" class="btn btn-secondary" value="Edit">
    </form>
    <br>
</main>
{% endblock %}

templates/form.html
{% extends "base.html" %}
{% block content %}
    <main class="px-3">
    <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="btn btn-secondary" type="submit" value="Send">
    </form>
    </main>
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% block content %}
     <main class="px-3">
     <br>
    <h1>About us...</h1>
    <p class="lead"><p>RentCar4U - short and long term car loan.<br>
    Rent a car fit to your needs.</p>
         <p>"Rent Car 4U" was established at the beginning of 2022. We are a company that provides car rental services.
             Our fleet, which is constantly expanding, consists of economics and premium class cars, which cause we will meet the requirements of every customer, even the most demanding.
             The company's office is in Szczecin at ul. Kochanowskiego 14. We invite you to use our services. <br>RentCat4U - the best quality, the best prices. </p>

  </main>

{% endblock %}

templates/nav_bar.html
<!-- Nav -->
<nav id="navbar" class="navbar">#}
        <ul>
             {% if user.is_authenticated %}
          <li><a class="nav-link scrollto " href="{% url "index" %}">Home</a></li>
          <li><a class="nav-link scrollto" href="{% url "profile_details" user.id %}">My account</a></li>
          <li><a class="nav-link scrollto" href="{% url "car_list" %}">List of all Cars</a></li>
          <li><a class="nav-link scrollto " href="{% url "car_add" %}">Add Car</a></li>
          <li><a class="nav-link scrollto" href="{% url "location_add" %}">Add Location</a></li>
          <li><a class="nav-link scrollto" href="{% url "car_rent" %}">Rent a Car</a></li>
          <li><a class="nav-link scrollto" href="{% url "user_rent_list" %}">My reservations</a></li>
          <li><a class="nav-link scrollto" href="{% url "rent_list" %}">All Reservations</a></li>
          <li><a class="nav-link scrollto" href="{% url "contact" %}">Contact Us</a></li>
          <li><a class="nav-link scrollto" href="{% url "logout" %}">Log out</a></li>
        </ul>
          {% else %}
          <li><a class="nav-link scrollto " href="{% url "index" %}">Home</a></li>
          <li><a class="nav-link scrollto " href="{% url "car_list" %}">List of all Cars</a></li>
          <li><a class="nav-link scrollto " href="{% url "create_user" %}">Create Account</a></li>
          <li><a class="nav-link scrollto " href="{% url "login" %}">Log in</a></li>
          <li><a class="nav-link scrollto " href="{% url "contact" %}">Contact Us</a></li>
          {% endif %}
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav>
<!-- Nav -->

templates/profile_details.html
{% extends "base.html" %}
{% block title %}
    <title>My account | RentCar4U</title>
    {% endblock %}

{% block content %}
    <h3>My Account:</h3>
    <tr>
        <th>First name: </th><td>{{ user.first_name}}</td><br>
        <th>Last name: </th><td>{{ user.last_name }}</td><br>
        <th>Email: </th><td>{{ user.email}}</td><br>
        <th>Tel. number: </th><td>{{ user.profile.tel_num}}</td><br>
        <th>Address: </th><td>{{ user.profile.address }}</td><br>
        <th>City: </th><td>{{ user.profile.city }}</td><br>
        <th>Zip code: </th><td>{{ user.profile.zip_code}}</td><br>
    </tr>
    <br>
    <a href="{{user.profile.get_update_url}}">Edit Profile</a>
{% endblock %}

templates/rent_details.html
{% extends "base.html" %}
{% block title %}
    <title>Car details | RentCar4U</title>
{% endblock %}

{% block content %}

    <table class="table table-striped" style="width:50%">
        <h3>Reservation details:</h3>
        <tr>
            <th>Reservation number [Res No.]:</th>
            <td>{{ rent.id }}</td>
        </tr>
        <tr>
            <th>User:</th>
            <td>{{ rent.user.username }}</td>
        </tr>
        <tr>
            <th>Car:</th>
            <td><a href="{{ rent.car.get_details_url }}">{{ rent.car }}</a></td>
        </tr>
        <tr>
            <th>Location:</th>
            <td>{{ rent.location }}</td>
        </tr>
        <tr>
            <th>Start date:</th>
            <td>{{ rent.start_date }}</td>
        </tr>
        <tr>
            <th>Start date:</th>
            <td>{{ rent.end_date }}</td>
        </tr>
        <tr>
            <th>Price per day:</th>
            <td>{{ price }}zł</td>
        </tr>
        <tr>
            <th>Summary price:</th>
            <td>{{ summary }}zł</td>
        </tr>
    </table>
    <br>
    </main>
{% endblock %}}

templates/rent_list.html
{% extends "base.html" %}
{% block title %}
    <title>Reservations list | RentCar4U</title>
{% endblock %}
{% block content %}
    <ul class="list-unstyled">
        {% for rent in object_list %}
            <li><a href="{{ rent.get_details_url }}">Res No. {{ rent.id }} </a></li>
            {#                <a href="{{ rent.get_edit_url }}">[Edit] </a>#}
            {#                <a href="{{ rent.get_delete_url }}"> [Cancel reservation]</a></p>#}
        {% endfor %}
    </ul>

{% endblock %}

templates/user_rent_list.html
{% extends "base.html" %}
{% block title %}
    <title>Reservations list | RentCar4U</title>
{% endblock %}
{% block content %}
    <ul class="list-unstyled">
        {% for rent in rents %}
            <li><a href="{{ rent.get_details_url }}">Res No. {{ rent.id }} </a></li>
                            <a href="{{ rent.get_edit_url }}">[Edit] </a>
                            <a href="{{ rent.get_delete_url }}"> [Cancel reservation]</a></p>
        {% endfor %}
    </ul>

{% endblock %}